emersion/go-message

charset/charset.go, charset/charset_test.go
Charset error happens when I try to fetch an e-mail with 'charset=gb2312'. I found that this charset is handled with simplifiedchinese.HZGB2312.  All going well with simplifiedchinese.GBK now.
=> Handle gb2312 charset with simplifiedchinese.GBK

charset/charset.go, charset/charset_test.go
I needed this for decoding some old messages. It would be nice if
https://github.com/emersion/go-message/blob/master/entity.go#L25 returned an
error if the encoding wasn't found.
=> Add windows-1250 encoding

header.go, header_test.go
I noticed that subjects sometimes are misformatted in my mail client due to improperly splitted quoted printable characters. Here is a small fix that should address this issue.
Thanks!
=> Don't split Quoted Printable characters during folding procedure

charset/charset.go, charset/charset_test.go
While this encoding name is non-standard, it does appear in the wild. As
its meaning is unambiguous, we should recognize and handle it (but not
emit it ourselves).
=> Handle the invalid "utf8" encoding

mail/address.go
This allows for headers which are encoded with an unusual encoding.
As promised....
There is no message.Decoder (re your IRC comment >and set WordDecoder to message.Decoder)
I assume you mean the CharsetReader?
=> mail: use message.CharsetReader in parseAddressList

charset/charset.go
Hi there! When using [aerc](https://git.sr.ht/~sircmpwn/aerc), I noticed that some messages in my inbox had declared their encoding "ansi_x3.4-1968", which resulted in some errors trying to decode them. It turns out this is just another possible name for ASCII. This patch allows any "ansi_x3.4-" name as a synonym for ASCII. When I apply this and build aerc, my issue is fixed.
Let me know if you have any suggestions!
=> Support ANSI x3.4 as a name for ASCII

mail/header.go, mail/header_test.go
I think that should be it, at least from the stuff that's in header.go.
As far as I understood the RFC, subject must not have a cfws and the Address fields are already parsed by the go stdlib.
=> mail/header: strip CFWS from date headers.

textproto/bench_test.go, textproto/header.go
Several preallocations and one clever trick.
Here is comparison with old code using benchmarks added in d569c5e:
```
benchmark                            old ns/op     new ns/op     delta
BenchmarkTextprotoReadHeader/1-4     16675         12950         -22.34%
BenchmarkTextprotoReadHeader/2-4     21488         16850         -21.58%
BenchmarkTextprotoReadHeader/3-4     36715         31491         -14.23%
benchmark                            old allocs     new allocs     delta
BenchmarkTextprotoReadHeader/1-4     165            106            -35.76%
BenchmarkTextprotoReadHeader/2-4     183            116            -36.61%
BenchmarkTextprotoReadHeader/3-4     359            277            -22.84%
benchmark                            old bytes     new bytes     delta …
```
=> textproto: Reduce amount of allocations where possible

textproto/header.go
It makes WriteHeader racy when used on the same Header object from
multiple goroutines.
=> textproto: Drop f.b assignment from WriteHeader

textproto/header.go, textproto/header_test.go
Textproto should throw an error and fail to parse a header if it
contains an invalid rather than preserving it as-is.
References: https://github.com/emersion/go-message/issues/68
I have very little Go experience, so let me know if there's any issues with this fix or if anything is non-idiomatic. I'm happy to clean things up :)
=> Add error on invalid header name characters

mail/header.go, mail/header_test.go
Those are defined in RFC 5322 section 3.6.4. We need to provide helpers
because the fields may contain CFWS.
~~We just use mail.ParseAddress and mail.ParseAddressList to avoid
building a msg-id parser. Maybe it's desirable to add a msg-id parser
upstream in net/mail.~~
Message identifiers are returned without the angle brackets, because the
RFC says:
> Semantically, the angle bracket characters are not part of the
> msg-id; the msg-id is what is contained between the two angle bracket
> characters.
Also, it's easier for the caller to add back the angle brackets if
needed rather than stripping them.
MsgIDList isn't the best name ever. The RFC defines the message-id token
for the Message-ID header field and the msg-id token for message
identifiers, hence this name. I wonder if we can come …
=> mail: add Header.MessageID and Header.MsgIDList

textproto/header.go, textproto/header_test.go
Limits specified allow header sections with total size up to ~3.8 MiB.
This should be enough for literally any message.
Closes #28.
Related to foxcpp/maddy#118.
=> textproto: Add limits for header field length and total amount of fields

textproto/header.go, textproto/header_test.go
Use only whitespace characters as a separator to fold lines according to the section 2.2.3 of RFC5322. It may increase number of cases where hard limit fallback is used, but it should prevent damaging encoded subjects.
Should fix #54
=> Fix incorrect line folding of RFC2047-encoded strings

mail/writer.go
`CreateWriter` does set Content-Type to `multipart/mixed` unconditionally.
This forces some mail clients into showing that attachments exist -- even if there are none (the multipart only contains one part).
As I still need a `multipart/alternative`, using `CreateSingleInlineWriter` is not sufficient. Thus I added `CreateInlineWriter` (returning an `*InlineWriter`) as the (missing) middle course.
=> Add CreateInlineWriter, allowing alternatives, but no attachments

textproto/header.go
This allows users to access the raw header field contents.
Closes: https://github.com/emersion/go-message/issues/91
=> textproto: add Header.Raw and HeaderFields.Raw

entity_test.go, writer.go
RFC 2045 specifies that any email conforming to this RFC MUST contain MIME-Version header.
=> Add MIME-Version header

charset/charset.go, charset/charset_test.go
Upstream go's x/text/encoding package has a bug that makes the
'hz-gb-2312' encoding crash (https://github.com/golang/go/issues/35118)
This was reported to go-message in
https://github.com/emersion/go-message/issues/95
This commit removes the offending encoding so that go-message can't crash if
people import the charset package. It should be reverted once the upstream
package is fixed by the go developers.
=> Remove hz-gb-2312 encoding as it can crash

textproto/header.go, textproto/header_test.go
Add checks for header field name according to RFC 6532 and disallow newline characters in field values.
Resolves #80
=> textproto: check header characters

charset.go, encoding.go, entity.go, entity_test.go
This allow us to use the go 1.13 error handling facility which is a bit cleaner
as it allows for a nested error lookup with
```
err = someTwoCallDeepGoMessageFunc()
if errors.Is(err, message.UnknownEncodingError) {
handleIt()
}
```
Else it gets really clunky, as the caller has to unwrap the error to the exact error
returned by go-message and then using message.IsUnknownEncoding(err).
To keep backwards compatibility I've left the helpers in, so there should be no
breaking changes.
=> Export Unknown{Charset,Encoding}Errors

mail/header.go, mail/header_test.go, mail/mail.go, mail/mail_test.go
See each commit.
Should we add `SetMessageID`, or wait till someone needs it?
cc @foxcpp
=> mail: add msg-id setters

charset.go, header_test.go
Related to issue https://github.com/emersion/go-message/issues/107; these tests should pass once we figure out what to do with #107
=> Ensure errors returned from fields.Text() verify IsUnknownCharset (fixes #107)

entity.go, entity_test.go
Entity.Walk is similar to filepath.Walk [1]: it iterates over all parts
in the entity tree.
There is no equivalent to SkipDir, because the whole tree will need to
be read anyway (ie. the performance benefits of filepath.SkipDir cannot
apply here).
WalkFunc paths are different from IMAP part paths: the root part
doesn't have a path equal to {1}, and indices start at 0. The former is
necessary to disambiguate between the root part and its first child if
it's multipart.
[1]: https://golang.org/pkg/path/filepath/#Walk
Closes: https://github.com/emersion/go-message/issues/88
=> message: introduce Entity.Walk

mail/address.go, mail/header_test.go
using a type alias allows users to provide a net/mail.Address wherever an
Address is expected, avoiding the conversion necessary until now.
Fixes https://github.com/emersion/go-message/issues/11
=> mail: use type aliases for Address

mail/address.go, mail/address_test.go, mail/header.go
This exposes essentially the same API as net/mail for parsing strings.
Doc strings should make it obvious that this should not be used on a header.
=> Export ParseAddressList and add ParseAddress for symetry

mail/writer.go, writer.go
If callers pass the same header to CreateSingleInlineWriter or similar methods,
the header gets modified in place, which means that the header of the caller
and the header of go-message go out of sync and subsequent operations on the
same header fail.
Operate on a copy in all paths that modify the header to avoid this issue.
=> operate on a copy of the header for write methods

textproto/header.go, textproto/header_test.go
Same as textproto.MIMEHeader.Values in the stdlib [1].
The doc comment says the returned slice is read-only, but we actually do
a copy. This is so we don't put ourselves into a corner and can change
how the function works internally in the future.
[1]: https://golang.org/pkg/net/textproto/#MIMEHeader.Values
=> textproto: introduce Header.Values

writer.go
Function `CreateWriter()` always set/reset header `Mime-Version: 1.0`. it was introduced by PR #90.
https://github.com/emersion/go-message/blob/master/writer.go#L77
In my case, i read message from `os.Stdin`, then write message to disk with `WriteTo()` (and it calls `CreateWriter()`). As you can imagine, the message already contains `Mime-Version:` header, for example:
```
Mime-Version: 1.0 (Mac OS X Mail 13.4 \(3608.120.23.2.4\))
```
go-message should respects existing header(s), only add if it's missing.
=> Respect existing `Mime-Version:` header

entity.go, entity_test.go, textproto/header.go, textproto/header_test.go
It's not really useful to individually check the line length or the
number of fields, what we really care about is the total header size.
This is also what net/http checks for.
Remove size checks from textproto, since callers can implement them. Use
a variant of io.LimitedReader in message instead.
=> Move header size restriction from textproto to message

go.mod, go.sum, mail/header.go
I'm not sure if there is a specific reason for doing it as it currently is? Anyhow, this pull request removes this otherwise unused external dependency and use strconv to base36 encode. This has the side effect of reducing allocations as well as improving execution times.  Output should be comparable;
```
Old: C9EDU8EPQBGY.1OPA7WEUKTFIY@hostname
New: C9EDU7U5NQNZ.1T2B0PIFP4V88@hostname
Old: C9EE4CRAIMU9.35K02SYKO9VWW@hostname
New: C9EE4C6I3XNX.2V6K31R712RT@hostname
```
And benchmark diff using `benchstat` when calling the `GenerateMessageID` function;
```
name                      old time/op    new time/op    delta
Header_GenerateMessageID    8.71µs ± 5%    6.59µs ±10%  -24.29%  (p=0.000 n=10+10)
name                      old alloc/op   new alloc/op   delta
Header_GenerateMessageID …
```
=> mail: use stdlib instead of external dependency

entity.go, entity_test.go
This provides a way to customise the behaviour of Read, starting with the max permissible size headers can be. Resolves #149
=> Introduce a new entity func ReadWithOptions. 

encoding.go, entity_test.go
=> Tolerate (incorrect) folding whitespace used in base64 encoded body content.

mail/header.go, mail/header_test.go
Prevent setting empty address list headers (to, from, cc, bcc). RFCC
5322 states that destination address list headers contain the field name
and one or more addresses, implying that empty headers are not allowed.
=> header: prevent setting empty address list headers

example_test.go
Just fixing a typo, it should be h2 instead of h1.
=> Fixing wrong var in example_test.go

mail/header.go
Usually the hostname of the local machine tends to be not unique nor a
FQDN. This brings multiple problems with it when sending messages using
such Message-ID.
First of all this makes go-message more compliant to RFC5322 [1] because
it recommends to use a FQDN on the right handed side of the @ in the
Message-ID. Second this also improves the situation with spam filters,
because some of them (for example rspamd) give a bad score for messages
without a FQDN in the Message-ID.
[1] https://www.rfc-editor.org/rfc/rfc5322.html#section-3.6.4
=> Add function to set Message-ID hostname manually

mail/header.go
This fixes a dropped `err` variable in the `mail` package.
=> mail: fix dropped error

encoding.go
TL;DR, without this patch, the following test would not pass:
```go
func TestLineWrapperShortWrite(t *testing.T) {
var sb strings.Builder
w := &lineWrapper{w: &sb, maxLineLen: 76}
b := []byte("The end.\r\n")
n, err := w.Write(b)
if err != nil {
t.Fatalf("Write() = %v", err)
}
if n != len(b) {
// FAILS HERE.
t.Errorf("Written = %d, want %d", n, len(b))
}
}
```
This is known as `io.ErrShortWrite`; I encountered it in `bytes.Reader.WriteTo` (via `io.Copy`):
```go
package bytes
...
// WriteTo implements the [io.WriterTo] interface.
func (r *Reader) WriteTo(w io.Writer) (n int64, err error) {
r.prevRune = -1
if r.i >= int64(len(r.s)) {
return 0, nil
}
b := r.s[r.i:]
m, err := w.Write(b)
if m > len(b) {
panic("bytes.Reader.WriteTo: invalid Write count")
}
r.i += int64(m)
n = int64(m)
if m != …
```
=> Fixup line wrapper short write bug

writer_test.go
Without the recent change of line wrapper implementation, this test is failing with the following error:
```
=== RUN   TestWriter_afterReading
writer_test.go:231: reformatted message differs:
--- /tmp/go-message-orig-2606107600.txt	2025-01-13 21:12:35.433528299 +0100
+++ /tmp/go-message-after-1462324866.txt	2025-01-13 21:12:35.433528299 +0100
@@ -83,7 +83,8 @@
app/compose.go | 24 ++++++++++++++++++------
1 file changed, 18 insertions(+), 6 deletions(-)
-diff --git a/app/compose.go b/app/compose.go
+diff --git a/app/compose.go b/app/co
+mpose.go
index 7a6a423c3ea3..e8a672479245 100644
--- a/app/compose.go
+++ b/app/compose.go
@@ -113,7 +114,8 @@
c.editor = nil
c.focusable = c.focusable[:len(c.focusable)-1]
if c.focused >= len(c.focusable) {
-@@ -1213,8 +1221,10 @@ func (c *Composer) …
```
=> writer: check that parsed messages can be reformatted verbatim

textproto/header.go
The doc incorrectly stated that the method requires the argument to have a comma character. Instead, it requires a colon.
=> Fix typo in the doc for (*Header).AddRaw method.
